In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.keras as keras
from keras.models import *

Using TensorFlow backend.


In [2]:
model = keras.models.load_model('sudoku.model')

In [3]:
def norm(a):
    
    return (a/9)-.5

def denorm(a):
    
    return (a+.5)*9

In [8]:
def inference_sudoku(sample):
    
    feat = sample
    
    while(1):
    
        out = model.predict(feat.reshape((1,9,9,1)))
        print(out.shape)
#         print(f'out:{out}')
        out = out.squeeze()
#         print(f'out: {out}')

        pred = np.argmax(out, axis=1).reshape((9,9))+1 
        prob = np.around(np.max(out, axis=1).reshape((9,9)), 2)
#         print(f'pred:{pred}, prob:{prob}')
        
        feat = denorm(feat).reshape((9,9))
#         print(f'feat: {feat}')
        mask = (feat==0)
#         print(f'mask: {mask}')
     
        if(mask.sum()==0):
            break
            
        prob_new = prob*mask
#         print(f'prob_new : {prob_new}')
    
        ind = np.argmax(prob_new)
#         print(f'ind: {ind}')
        x, y = (ind//9), (ind%9)
#         print(f'x:{x} y:{y}')

        val = pred[x][y]
        feat[x][y] = val
        feat = norm(feat)
    
    return pred

In [9]:
def solve_sudoku(game):
    
    game = game.replace('\n', '')
    game = game.replace(' ', '')
    game = np.array([int(j) for j in game]).reshape((9,9,1))
    game = norm(game)
    game = game.reshape((1,9,9,1))
#     out = model.predict(game)
#     print(out.shape)
#     print(out.squeeze().shape)
#     out = out.squeeze()
    game = inference_sudoku(game)
    return game

In [10]:
game = '''
          0 8 0 0 3 2 0 0 1
          7 0 3 0 8 0 0 0 2
          5 0 0 0 0 7 0 3 0
          0 5 0 0 0 1 9 7 0
          6 0 0 7 0 9 0 0 8
          0 4 7 2 0 0 0 5 0
          0 2 0 6 0 0 0 0 9
          8 0 0 0 9 0 3 0 5
          3 0 0 8 2 0 0 1 0
      '''

game = solve_sudoku(game)

print('solved puzzle:\n')
print(game)

(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
(1, 81, 9)
(81, 9)
solved puzzle:

[[4 8 9 5 3 2 7 6 1]
 [7 1 3 4 8 6 5 9 2]
 [5 6 2 9 1 7 8 3 4]
 [2 5 8 3

In [7]:
np.sum(game, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45], dtype=int64)